name1 = input ('What is your first name?')
name2 = input ('What is your last name?')
jobtitle = input ('What is your job title?')
id = input ('What is your ID number?')
email = input ('What is your email address?')
phone = input ('What is your phone number?')
hair = input ('What color is your hair?')
eyes = input ('What color are your eyes?')
month = input (f'What month did you start work as a {jobtitle.title()}?')
training = input ('Are you still in training? (yes or no)')
print('The ID Card is:')
print('-'*50)
print(f'{name2.upper()}, {name1}')
print(f'{jobtitle.title()}')
print(f'ID: {id}')
print(' ')
print(f'{email.lower()}')
print(f'{phone}')
print(' ')
print(f'Hair: {hair.title() :15}Eyes: {eyes.title() :5}')
print(f'Month: {month.title() :14}Training: {training.title() :5}')
print('-'*50)