print('Welcome to MadLibs! Please respond to the following prompts:')

adj1 = input('Enter an Adjective:')
adverb = input('Enter an Adverb:')
adj2 = input('Enter an Adjective:')
part = input('Enter a Plural Body Part:')
verb = input('Enter a Verb:')
adj3 = input('Enter an adjective:')
cut_of_meat = input('Enter name of a cut of meat:')
name = input('Enter a Name:')
room_in_house = input('Enter the name of a room in a house:')
adj4 = input('Enter an Adjective:')

print(f'It was a {adj1}, warm afternoon, and I woke up from my {adverb} nap.')
print(f'I walked outside, and felt the {adj2} wind in my {part}.')
print(f'I continued to {verb} outside until it was dark out, then I headed in')
print(f'for dinner. When I walked in, I smelled the {adj3} {cut_of_meat} that ')
print(f'{name.title()} was grilling in the {room_in_house}. In the end it tasted {adj4}.')